- request:
    url: ^/provincias
    method: GET
  response:
    - status: 200
      latency: 5000
      headers:
        content-type: application/json
        access-control-allow-origin: "*"
        access-control-allow-method: "*"
      file: location/location-200.json

- request:
    url: ^/vehiculos/marcas
    method: GET
  response:
    - status: 200
      latency: 5000
      headers:
        content-type: application/json
        access-control-allow-origin: "*"
        access-control-allow-method: "*"
      file: vehicles/marcas-200.json

- request:
    url: ^/vehiculos/marcas
    method: GET
  response:
    - status: 200
      latency: 5000
      headers:
        content-type: application/json
        access-control-allow-origin: "*"
        access-control-allow-method: "*"
      file: vehicles/modelos-200.json

- request:
    url: ^/vehiculos/marcas
    method: GET
  response:
    - status: 200
      latency: 5000
      headers:
        content-type: application/json
        access-control-allow-origin: "*"
        access-control-allow-method: "*"
      file: vehicles/versiones-200.json

- request:
    url: ^/coberturas
    method: GET
  response:
    - status: 200
      latency: 5000
      headers:
        content-type: application/json
        access-control-allow-origin: "*"
        access-control-allow-method: "*"
      file: coverage/coverage-200.json

